### ISSUE TITLE
/data/webred/all_chains.json

### ISSUE THREAD

**Issue by cx51666666** [yym6472/KBQARelationLearning#1]
How to generate or download all_chains. json file?
![image](https://user-images.githubusercontent.com/43124010/144337504-918c959a-d429-40e7-8691-13f7a5279961.png)

**Comment by cx51666666** [comment]
![image](https://user-images.githubusercontent.com/43124010/144390533-232947f1-4d70-40c1-ab36-7a262a9e59ea.png)
IndexError: tuple index out of range

Errors occur during validation

**Comment by cx51666666** [comment]
![image](https://user-images.githubusercontent.com/43124010/144390872-01fd06b7-3a5a-4e90-8546-600864bc0c5a.png)

**Comment by yym6472** [comment]
Sorry for the late reply, the `all_chains. json` is not used in final experiments and can be ignored, just comment this line: `update_chain_info(...)`.
